CREATE SCHEMA `microservices` ;

use `microservices`;
CREATE TABLE `ACCOUNTS` (
`ACCOUNT_NUMBER` INT NOT NULL AUTO_INCREMENT,
`CUSTOMER_ID` INT NOT NULL,
`ACCOUNT_TYPE` VARCHAR(200) NOT NULL,
`BRANCH_ADDRESS` VARCHAR(200) NOT NULL,
`CREATE_DATE` DATE DEFAULT NULL,
PRIMARY KEY(`ACCOUNT_NUMBER`)
);

CREATE TABLE `CUSTOMER` (
`CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
`NAME` VARCHAR(100) NOT NULL,
`EMAIL` VARCHAR(100) NOT NULL,
`MOBILE_NUMBER` VARCHAR(20) NOT NULL,
`CREATE_DATE` DATE DEFAULT NULL,
PRIMARY KEY(`CUSTOMER_ID`)
);

INSERT INTO `CUSTOMER` (`NAME`, `EMAIL`, `MOBILE_NUMBER`, `CREATE_DATE`)
	VALUES ('SATINDER','SATINDER@GMAIL.COM','9954593057',CURDATE());
	
INSERT INTO `ACCOUNTS` (`CUSTOMER_ID`,`ACCOUNT_NUMBER`, `ACCOUT_TYPE`, `BRANCH_ADDRESS`, `CREATE_DATE`)
	VALUES (1,18657620, 'SAVING','AMBALA',CURDATE());

commit;

